<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FuzzySharp" Version="2.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.4" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.4" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.4" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.4" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.4" />
    <PackageReference Include="Spectre.Console" Version="0.54.0" />
    <PackageReference Include="System.IO.Hashing" Version="10.0.4" />
  </ItemGroup>

</Project>
